server:
  port: 8888

management:
  context-path: /admin
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health

spring:
  datasource:
    username: clients
    password: '{cipher}AQAai7rHPQZ1/4/JEMWSopials5/T6Hkvdtt+258AF6MbpqjpTl6S2McnogO/PAYx8vMpNpwYzFFps37Z+/SrikS19bVEyI+dRiRtKNftgl6k/HtZPWUHLTaEeXEq0IRUJEXNaZLvFBGpEczfrrVLNel4Rrna9CZ4KeGBkauMbtIGhRfy1U+5DOvd0Ahq4YBqRq3xdRaTZ0Ks3WUoqkQYbZmaO98DpzzMhd2Z6vopUmm/XQ/mU8v9xWvZYB6JepFEWsJg8rtCp5UXoyKAqc8rzfS9Zv7E5yqfgq+EcqzYy23ppCQrPiGqurQp/2DsS/a4OrpX+uHnQaWiBAGf1xmIn6qLz0JLPCfqeQ3gu/T2Oi5n6NARuqV2pmgvGPACSxCEc0='
  cloud:
    config:
      server:
        prefix: /server # change server prefix so we can handle our own endpoints as well without conflicts
        git:
          uri: https://github.com/pezhman32/spring-cloud-config-repo.git
          basedir: target/config

---
spring:
  profiles: cloud
eureka:
  password: password
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:${eureka.password:}@${PREFIX:}eureka.${application.domain:cfapps.io}}/eureka/

